# Generated by Django 4.1.8 on 2023-05-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='is_using',
            field=models.BooleanField(verbose_name='是否启用'),
        ),
    ]
