# Generated by Django 4.1.8 on 2023-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_offermodel_is_using'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='school',
            field=models.CharField(default='学校名称', max_length=50, verbose_name='学校名称'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='time',
            field=models.CharField(default='时间', max_length=50, verbose_name='时间'),
        ),
    ]
