# Generated by Django 4.1.8 on 2023-06-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_studentmodel_type'),
        ('offer', '0003_offermodel_school_offermodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='type',
            field=models.ForeignKey(blank=True, help_text='学生类型', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.typemodel', verbose_name='学生类型'),
        ),
    ]
