# Generated by Django 4.1.8 on 2023-06-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='school',
            field=models.CharField(default='学校名称', max_length=30, verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='offermodel',
            name='time',
            field=models.CharField(default='时间', max_length=20, verbose_name='时间'),
        ),
    ]
