# Generated by Django 4.1.8 on 2023-06-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_offermodel_school_alter_offermodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='prefix',
            field=models.CharField(default='服务器前缀', max_length=50, verbose_name='服务器前缀'),
        ),
    ]
