# Generated by Django 4.1.8 on 2023-06-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_offermodel_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offermodel',
            old_name='prefix',
            new_name='web_path',
        ),
    ]
