# Generated by Django 4.1.8 on 2023-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.CharField(help_text='身份证号', max_length=18, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('name', models.CharField(help_text='姓名', max_length=20, verbose_name='姓名')),
                ('student_id', models.CharField(help_text='学号', max_length=20, verbose_name='学号')),
                ('sex', models.CharField(choices=[(1, '男'), (0, '女')], help_text='性别', max_length=1, verbose_name='性别')),
                ('admission_date', models.SmallIntegerField(help_text='入学日期', verbose_name='入学日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('access_count', models.IntegerField(default=0, help_text='访问次数', verbose_name='访问次数')),
            ],
        ),
    ]
