# Generated by Django 4.1.8 on 2023-05-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AlterModelTable(
            name='studentmodel',
            table='student',
        ),
    ]
