# Generated by Django 4.1.8 on 2023-05-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentmodel_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='class_num',
            field=models.CharField(default=1, help_text='班级', max_length=20, verbose_name='班级'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='student_id',
            field=models.CharField(help_text='考号', max_length=20, unique=True, verbose_name='考号'),
        ),
    ]
