# Generated by Django 4.1.8 on 2023-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentmodel_class_num_alter_studentmodel_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='class_num',
            field=models.SmallIntegerField(help_text='班级', verbose_name='班级'),
        ),
    ]
