# Generated by Django 4.1.8 on 2023-05-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentmodel_class_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='access_count',
            field=models.SmallIntegerField(default=0, help_text='访问次数', verbose_name='访问次数'),
        ),
    ]
