# Generated by Django 4.1.8 on 2023-06-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentmodel_access_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='offer',
            field=models.FileField(blank=True, help_text='录取通知书', null=True, upload_to='offer/student_offer', verbose_name='录取通知书'),
        ),
    ]
