# Generated by Django 4.1.8 on 2023-06-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentmodel_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='学生类型', max_length=50, verbose_name='学生类型')),
            ],
            options={
                'verbose_name': '学生类型',
                'verbose_name_plural': '学生类型',
                'db_table': 'type',
            },
        ),
    ]
