# Generated by Django 4.1.8 on 2023-06-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_typemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='type',
            field=models.ForeignKey(blank=True, help_text='学生类型', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.typemodel', verbose_name='学生类型'),
        ),
    ]
