# Generated by Django 4.1.8 on 2023-07-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_studentmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='class_num',
            field=models.CharField(help_text='班级', max_length=50, verbose_name='班级'),
        ),
    ]
