# Generated by Django 4.1.8 on 2023-07-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_studentmodel_class_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='class_num',
            field=models.CharField(help_text='班级', max_length=60, verbose_name='班级'),
        ),
    ]
